//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportation.DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Driver()
        {
            this.tbl_DriverTransaction = new HashSet<tbl_DriverTransaction>();
        }
    
        public int Id { get; set; }
        public string DriverName { get; set; }
        public string DriverFamily { get; set; }
        public string CarTag { get; set; }
        public string CarName { get; set; }
        public string CarColor { get; set; }
        public string NationalCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DriverTransaction> tbl_DriverTransaction { get; set; }
    }
}
