//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace Transportation.DataLayer.Models
{

    public partial class TransportationContext : DbContext
    {
        public TransportationContext()
            : base("name=TransportationContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Driver> tbl_Driver { get; set; }
        public virtual DbSet<tbl_DriverTransaction> tbl_DriverTransaction { get; set; }
        public virtual DbSet<tbl_DriverTransactionType> tbl_DriverTransactionType { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    }
}
